# Generated by Django 3.0.3 on 2020-02-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comments',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=1000, null=True),
        ),
    ]
